# golangci-lint configuration v2
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

output:
  formats:
    text:
      path: stdout
      colors: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
